<link rel="stylesheet" type="text/css" href="../resources/css/vue_sock.css">

<div class="nav-bar"></div>
<div id="app">

    <div class="cart"
        @mouseover="hover = true"
        @mouseleave="hover = false"
        :class="{ active: hover }">

        <p>Cart: {{ cart.length }}</p>
        <div v-if="hover">This is a secret message.</div>
    </div>
    <div v-if="hover">This is a secret message.</div>

    <product :premium="premium" @add-to-cart="updateCart"></product>
    <product @add-to-cart="updateCart"></product>
    <product @add-to-cart="updateCart"></product>
  
</div> 

 <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js" defer></script>
 <script src="../resources/js/vue_sock.js" defer></script>