<link rel="stylesheet" type="text/css" href="../resources/css/vue_sock.css">

<div class="nav-bar"></div>
<div id="app">

    <div class="cart"
        @mouseover="hover = true"
        @mouseleave="hover = false"
        :class="{ active: hover }">

        <p>Cart: {{ cart.length }}</p>
        <div v-if="hover">
            <table v-if="cart.length>0" class="cart-block__cart-tb">
                <thead>
                    <tr>
                        <th class="cart-block__product-info-th">Thông tin</th>
                        <th class="cart-block__quantity-th">Số lượng</th>
                        <th class="cart-block__price-th">Thành tiền</th>
                        <th class="cart-block__control-th">Thao tác</th>
                    </tr>
                </thead>

                <tbody>
                    <tr v-for="product in cart">
                        <td>{{product.variantId}}</td>
                        <td>{{product.variantColor}}</td>
                        <td class="cart-block__quantity-td">
                            <div class="my-quantity-control">
                                <div class="my-quantity-control__btn -minus-btn">-</div>
                                <input type="number" class="my-quantity-control__input" min="1" max="99" />
                                <div class="my-quantity-control__btn -plus-btn">+</div>
                            </div>
                        </td>
                        <td>
                            <button
                                class="cart-block__control-btn"
                            >
                                <span class="cart-block__control-btn__icon"><i class="fal fa-trash-alt"></i></span> Xóa
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
    <div v-if="hover">This is a secret message.</div>

    <product :premium="premium" @add-to-cart="updateCart"></product>
    <product @add-to-cart="updateCart"></product>
    <product @add-to-cart="updateCart"></product>
  
</div> 

<div id="emit-example-simple">
  <welcome-button v-on:welcome="sayHi"></welcome-button>
</div>

 <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js" defer></script>
 <script src="../resources/js/vue_sock.js" defer></script>