<link rel="stylesheet" type="text/css" href="../resources/css/vue_sock.css">

<div class="nav-bar"></div>
<div id="app">
  
  <div class="product-image">
    <img :src="image" />
  </div>

  <div class="product-info">
    <h1>{{ product }}</h1>
  </div>

</div> 

 <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js" defer></script>
 <script src="../resources/js/vue_sock.js" defer></script>