<form action="" method="get" name="test-form">
    <div>
        Username: <input type="text" name="username">
    </div>

    <div>
        City: <input type="text" name="city">
    </div>

    <div>
        <input type="submit" value="submit">
    </div>
</form>

<?php
    
    //option1: just use for form has a get method
    //getQuery($name, $filter, $default, $notAllowEmpty)
    //$params = $this->request->getQuery();

    //option2: editor could support reminding systax
   
    $request    = new \Phalcon\Http\Request();
    $di         = new \Phalcon\Di\FactoryDefault();
    $request->setDI($di);
    $params     = $request->getQuery();
    $username   = $request->getQuery("username", "float", "username default", true); //just keep float
    $city       = $request->getQuery("city", "lower", "city default", false);     //convert everything to lower    
    $method     = $request->getMethod(); 


    echo "<pre>";
        print_r($params);
    echo "</pre>";

    echo '<h3 style="color:red"> Username: '.$username.'</h3>';
    echo '<h3 style="color:blue"> City: '.$city.'</h3>';
    echo '<h3 style="color:blue"> Method: '.$method.'</h3>';

    if($request->hasQuery("username")){
        echo "yes";
    }else{
        echo "no";
    }





?>