<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style type="text/css">
        .header{
            background-color: yellow;
            height: 50px;
        } 

        .middle{
            border: 5px solid red;
            height: 500px;
        }

        .after{
            border: 10px solid black;
            background-color: deeppink;
            height: 350px;
            padding: 10px;
        }
        
        .before{
            border: 10px solid black;
            background-color: hotpink;
            height: 250px;
            padding: 10px;
        }
        .footer{
            background-color: pink;
            height: 50px;
        }

        .layout1{
            background-color:green;
            height: 400px;
            color: white;
        }

        .layout2{
            background-color: blue;
            height: 400px;
            color: white;
        }

        .index1{
            background-color: brown;
            height: 50px;
            color: white;
        }

        .index2{
            background-color: blue;
            height: 50px;
            color: white;
        }

    </style>
</head>
<body>
    <!-- main layout of hello module, use for all controllers -->
    <div class ="header"> 
        <h1>Main Layout - Header</h1>


        <!-- get layout of seperate controller 
        default (indexcontroller - indexAction) -->
        <?php
            echo $this->getContent();
        ?>
    </div>

    <div class ="middle"> 
        <h1>Main Layout - Middle</h1>
    </div>

    <div class ="footer"> 
        <h1>Main Layout - Footer</h1>
    </div>
</body>
</html>





