<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Insert title here</title>
</head>
<body>
    <h1>Form  post-get</h1>
    <!-- after submitting, it accesses the action with /post-router link -->
    <form action="/post-router" method="post">
        <input type="submit" value="post-form">    
    </form>

    <form action="/get-router" method="get">
        <input type="submit" value="get-form">    
    </form>

    <form action="/via-post" method="post">
        <input type="submit" value="via-form">    
    </form>
    
</body>
</html>